<?php

namespace Page;

use Behat\Mink\Driver\Selenium2Driver;
use Behat\Mink\Element\NodeElement;
use Behat\Mink\Session;
use Exception;
use SensioLabs\Behat\PageObjectExtension\PageObject\Page;
use SensioLabs\Behat\PageObjectExtension\PageObject\Factory;

class BasePage extends Page {

  use \HelpTrait;

  protected $elements = [

  ];

  public static $data;

  public function __construct(Session $session, Factory $factory, array $parameters) {
    parent::__construct($session, $factory, $parameters);
  }

  /**
   * @param string $name
   *
   * @return \SensioLabs\Behat\PageObjectExtension\PageObject\Page
   * @throws \Exception
   */
  public function getPage($name) {
    if ($this->getDriver() instanceof Selenium2Driver) {
      $this->waitAjax();
    }
    return parent::getPage($name); // TODO: Change the autogenerated stub
  }

  /**
   * @param string $name
   *
   * @return \SensioLabs\Behat\PageObjectExtension\PageObject\Element
   * @throws \Exception
   */
  public function getElement($name) {
    if ($this->getDriver() instanceof Selenium2Driver) {
      $this->waitAjax();
    }    
     return parent::getElement($name);
  }

  /**
   * Return a current page url.
   * 
   * @return string
   */
  public function getCurrentUrl() {
    return $this->getDriver()->getCurrentUrl();
  }

  /**
   * Wait for AJAX to finish.
   */
  public function waitAjax($time = 30) {
    $time = $time * 1000;
    $driver = $this->getDriver();
    // Simple wait ajax to finish on the page.
    $driver->wait($time, '(typeof(jQuery)=="undefined" || (0 === jQuery.active && 0 === jQuery(\':animated\').length))');

    // Additionally we check if any ajax attributes on the page are active.
    try {
      $this->spin(function() use ($driver) {
        // Return false and wait if an ajax element on the page.
        $selectors = ['.j2tajax-progress'];
        foreach ($selectors as $css) {
          $el = $this->find('css', $css);
          if ($el instanceof NodeElement) {
            return !$el->isVisible();
          }
        }
        // And stop waiting if no ajax elements on the page.
        return TRUE;
      });
    }
    catch (Exception $e) {
      throw new Exception($e->getMessage() . ' ' . $this->getCurrentUrl());
    }
   }

  /**
   * Scroll element into view before interact with it.
   *
   * @param $scrollable_area
   * @param $target_selector
   * @throws Exception
   *
   */
  public function scrollIntoView($scrollable_area, $target_selector) {
    if (!$this->getDriver() instanceof Selenium2Driver || strlen($target_selector) < 2) {
      return;
    }

    $script = sprintf("
      jQuery('%s').animate({
        scrollTop: jQuery('%s').offset().top - 100
      }, 1000);",
      $scrollable_area, $target_selector);
    // Execute the script.
    try {
      $this->getDriver()->executeScript($script);
    }
    catch (Exception $e) {
      // Do nothing.
    }
    // Wait till this script scroll element into view.
    $this->waitAjax();
  }

}
