<?php

namespace Page;

use Behat\Mink\Driver\Selenium2Driver;
use Behat\Mink\Element\NodeElement;
use Behat\Mink\Session;
use Exception;
use SensioLabs\Behat\PageObjectExtension\PageObject\Page;
use SensioLabs\Behat\PageObjectExtension\PageObject\Factory;

class BasePage extends Page {

  use \HelpTrait;

  protected $elements = [

  ];

  public static $data;

  public function __construct(Session $session, Factory $factory, array $parameters) {
    parent::__construct($session, $factory, $parameters);
  }

  /**
   * @param string $name
   *
   * @return \SensioLabs\Behat\PageObjectExtension\PageObject\Page
   * @throws \Exception
   */
  public function getPage($name) {
    if ($this->getDriver() instanceof Selenium2Driver) {
      $this->waitAjax();
    }
    return parent::getPage($name); // TODO: Change the autogenerated stub
  }

  /**
   * @param string $name
   *
   * @return \SensioLabs\Behat\PageObjectExtension\PageObject\Element
   * @throws \Exception
   */
  public function getElement($name) {
    if ($this->getDriver() instanceof Selenium2Driver) {
      $this->waitAjax();
    }    
     return parent::getElement($name);
  }

  /**
   * Return a current page url.
   * 
   * @return string
   */
  public function getCurrentUrl() {
    return $this->getDriver()->getCurrentUrl();
  }

  /**
   * Wait for AJAX to finish.
   */
  public function waitAjax($time = 30) {
    $time = $time * 1000;
    $driver = $this->getDriver();
    // Simple wait ajax to finish on the page.
    $driver->wait($time, '(typeof(jQuery)=="undefined" || (0 === jQuery.active && 0 === jQuery(\':animated\').length))');

    // Additionally we check if any ajax attributes on the page are active.
    try {
      $this->spin(function() use ($driver) {
        // Return false and wait if an ajax element on the page.
        $selectors = ['.j2tajax-progress'];
        foreach ($selectors as $css) {
          $el = $this->find('css', $css);
          if ($el instanceof NodeElement) {
            return !$el->isVisible();
          }
        }
        // And stop waiting if no ajax elements on the page.
        return TRUE;
      });
    }
    catch (Exception $e) {
      throw new Exception($e->getMessage() . ' ' . $this->getCurrentUrl());
    }
   }

}
